### PR TITLE
Avoid some YSOD's and null checks as seen in #31

### PR DESCRIPTION
**Pull request by kgiszewski**

### CODE REVIEW

**Comment by kgiszewski** [comment]
Would it be worth returning a default value based on the property type? And if so, how would it be determined?

**Comment by mattbrailsford** [comment]
@kgiszewski looking at your comments on #31 it doesn't sound like it's the same issue. Can you explain the problem you are having? and why this fix is needed?

**Comment by mattbrailsford** [comment]
PS I don't think you'd be able to determine a default value based on the wrapped property editor, as it all depends on the value converters registered for the inner property editor.

**Comment by kgiszewski** [comment]
@mattbrailsford Vorto newbie here. I didn't realize Vorto wrapped other datatypes. Wrongly assumed it was strings only :) Definitely see the sophistication now :+1: 

I didn't setup Vorto on the site I'm having issues with. However, I have to null check the Vorto getter since it's returning null and due to issue #31.

Was hoping to avoid the null check since I have to further process the return value after it is returned.

Moving conversation back to #31.

**Pull request closed without merging**
